desc "Aplicación"
task :default => :server

desc "Servidor"
task :server do
  sh "rackup"
end

desc "Ejecutar todas las Pruebas Unitarias"
task :test do 
	sh "ruby --color --format documentation -Ilib test/test_rps.rb"
end