desc "Aplicación"
task :default => :server

desc "Servidor"
task :server do
  sh "rackup"
end

desc "Ejecutar los Test Rspec"
task :spec do
	sh "rspec --color --format documentation spec/rsack/server_spec.rb"
end
